In [2]:
import numpy as np 

# [OrderID, CustomerAge, ItemsCount, TotalAmount, Discount]
orders = np.array([
    [101, 22, 2, 500, 50],
    [102, 35, 5, 1500, 200],
    [103, 28, 1, 300, 20],
    [104, 45, 3, 1200, 150],
    [105, 32, 4, 2000, 300],
    [106, 26, 2, 700, 70],
    [107, 38, 6, 2500, 400],
    [108, 30, 3, 1000, 100]
])


## Print all Total Amount values

In [3]:
print("Total Amount Values: ", orders[:,3])

Total Amount Values:  [ 500 1500  300 1200 2000  700 2500 1000]


## Print all Discount values

In [4]:
print("All the Discounts Values: ", orders[:,4])

All the Discounts Values:  [ 50 200  20 150 300  70 400 100]


## Print first 4 orders

In [5]:
print("First 4 Orders",orders[:4:])

First 4 Orders [[ 101   22    2  500   50]
 [ 102   35    5 1500  200]
 [ 103   28    1  300   20]
 [ 104   45    3 1200  150]]


## Find minimum and maximum Total Amount

In [ ]:
# Maximum Amount

amount_column = orders[:,3]

max_amount = np.argmax(amount_column)

print(" Customer with Maximum Amount: ",orders[max_amount])


# Minimum Amount 

min_amount = np.argmin(amount_column)

print(" Customer with Minimum Amount: ",orders[min_amount])

Maximum Amount:  [ 107   38    6 2500  400]
Maximum Amount:  [103  28   1 300  20]


## Find order with minimum discount

In [ ]:
discount_column = orders[:,4]
min_discount = np.argmin(discount_column)
print("Customer With minimum amount: ", orders[min_discount])

Patient With minimum amount:  [103  28   1 300  20]


## Find average discount

In [ ]:
discount_column = orders[:,4]
print("Average discount Per Customer: ", np.mean(discount_column))

Average discount Per patient:  161.25


## Print orders where Total Amount > 1000

In [ ]:
print("Customer having amount more than 1000:", orders[orders[:,3]>1000])

Patients having amount more than 1000: [[ 102   35    5 1500  200]
 [ 104   45    3 1200  150]
 [ 105   32    4 2000  300]
 [ 107   38    6 2500  400]]


## Customer Age between 25 and 35

In [24]:
print("Customer Age between 25 and 35:", orders[(orders[:,1]>=25) & (orders[:,1]<=35)])

Customer Age between 25 and 35: [[ 102   35    5 1500  200]
 [ 103   28    1  300   20]
 [ 105   32    4 2000  300]
 [ 106   26    2  700   70]
 [ 108   30    3 1000  100]]
