In [1]:
import numpy as np 

# [OrderID, CustomerAge, ItemsCount, TotalAmount, Discount]
orders = np.array([
    [101, 22, 2, 500, 50],
    [102, 35, 5, 1500, 200],
    [103, 28, 1, 300, 20],
    [104, 45, 3, 1200, 150],
    [105, 32, 4, 2000, 300],
    [106, 26, 2, 700, 70],
    [107, 38, 6, 2500, 400],
    [108, 30, 3, 1000, 100]
])


## Print all Total Amount values

In [2]:
print("Total Amount Values: ", orders[:,3])

Total Amount Values:  [ 500 1500  300 1200 2000  700 2500 1000]


## Print all Discount values

In [3]:
print("All the Discounts Values: ", orders[:,4])

All the Discounts Values:  [ 50 200  20 150 300  70 400 100]


## Print first 4 orders

In [4]:
print("First 4 Orders",orders[:4:])

First 4 Orders [[ 101   22    2  500   50]
 [ 102   35    5 1500  200]
 [ 103   28    1  300   20]
 [ 104   45    3 1200  150]]


## Find minimum and maximum Total Amount

In [5]:
# Maximum Amount

amount_column = orders[:,3]

max_amount = np.argmax(amount_column)

print(" Customer with Maximum Amount: ",orders[max_amount])


# Minimum Amount 

min_amount = np.argmin(amount_column)

print(" Customer with Minimum Amount: ",orders[min_amount])

 Customer with Maximum Amount:  [ 107   38    6 2500  400]
 Customer with Minimum Amount:  [103  28   1 300  20]


## Find order with minimum discount

In [6]:
discount_column = orders[:,4]
min_discount = np.argmin(discount_column)
print("Customer With minimum amount: ", orders[min_discount])

Customer With minimum amount:  [103  28   1 300  20]


## Find average discount

In [7]:
discount_column = orders[:,4]
print("Average discount Per Customer: ", np.mean(discount_column))

Average discount Per Customer:  161.25


## Print orders where Total Amount > 1000

In [8]:
print("Customer having amount more than 1000:", orders[orders[:,3]>1000])

Customer having amount more than 1000: [[ 102   35    5 1500  200]
 [ 104   45    3 1200  150]
 [ 105   32    4 2000  300]
 [ 107   38    6 2500  400]]


## Customer Age between 25 and 35

In [9]:
print("Customer Age between 25 and 35:", orders[(orders[:,1]>=25) & (orders[:,1]<=35)])

Customer Age between 25 and 35: [[ 102   35    5 1500  200]
 [ 103   28    1  300   20]
 [ 105   32    4 2000  300]
 [ 106   26    2  700   70]
 [ 108   30    3 1000  100]]


##  Problem: Top 2 Highest Discount Orders

In [ ]:
discount_column = orders[:,4]
print(discount_column)

top_2 = np.argsort(discount_column)
top_2_idx = top_2[-2:]
print(top_2_idx)

top_2_order = orders[top_2_idx]
print(top_2_order)



[ 50 200  20 150 300  70 400 100]
[4 6]
[[ 105   32    4 2000  300]
 [ 107   38    6 2500  400]]


## Top 3 Orders (Only ID + Amount)

In [ ]:
amount_id= orders[:,3]
print(amount_id)

# sorting the array
sorted_column = np.argsort(amount_id)
print(sorted_column)

top_3 = sorted_column[-3:]

print("Top 3 orders with id and amount : ", (orders[top_3][:,[0,3]]))





[ 500 1500  300 1200 2000  700 2500 1000]
[2 0 5 7 3 1 4 6]
Top 3 orders:  [[ 102 1500]
 [ 105 2000]
 [ 107 2500]]


In [36]:
print(sorted_column)
result = (orders[sorted_column])
print("highest total amount come first: \n \n" ,result[::-1])

[2 0 5 7 3 1 4 6]
highest total amount come first: 
 
 [[ 107   38    6 2500  400]
 [ 105   32    4 2000  300]
 [ 102   35    5 1500  200]
 [ 104   45    3 1200  150]
 [ 108   30    3 1000  100]
 [ 106   26    2  700   70]
 [ 101   22    2  500   50]
 [ 103   28    1  300   20]]
