In [2]:

import numpy as np

# [PatientID, Age, HeartRate, BP, SugarLevel]
patients = np.array([
    [1, 25, 72, 120, 90],
    [2, 40, 85, 140, 110],
    [3, 60, 78, 130, 150],
    [4, 35, 90, 150, 95],
    [5, 50, 88, 145, 130]
])

## Find minimum age

In [3]:
min_index = np.argmin(patients[:,1])
print(min_index)
print("Minimum Age:", patients[min_index,1])
print("Patient Details:", patients[min_index])

0
Minimum Age: 25
Patient Details: [  1  25  72 120  90]


## Find Maximum Age 

In [4]:
max_age = np.argmax(patients[:,1])
print(max_age)

# Printing the age of the Patients

print("Maximum age of the patients is: ", patients[max_age,1])

print("Details of the Patient: ", patients[max_age])

2
Maximum age of the patients is:  60
Details of the Patient:  [  3  60  78 130 150]


## Average Heart Rate of all patients

In [5]:
avg_rate =  patients[:1,2]
print(avg_rate)
print((avg_rate))

[72]
[72]


## B.P Values of all the patients

In [18]:
print("Bp Vlaues: ", patients[:,3] )

Bp Vlaues:  [120 140 130 150 145]


## Highest Sugar Patient

In [23]:
high_sugar = patients[:,4]

high_sugar_index = np.argmax(high_sugar)
print("Patients with highest BP: ",high_sugar_index)

print("Details of Highest BP: ",patients[2])

Patients with highest BP:  2
Details of Highest BP:  [  3  60  78 130 150]


## Minimum Bp

In [25]:
min_bp  = patients[:,3]
print(min_bp)

min_bp_index = np.argmin(min_bp)
print("Patient with Minimum BP: ", patients[min_bp_index])

[120 140 130 150 145]
Patient with Minimum BP:  [  1  25  72 120  90]


## Patient Detail having more than 85


In [ ]:

result = patients[patients[:,2]>=85]

print("Patients with High Heart Rate: ",result)

patient list of heartrate:  [72 85 78 90 88]
Patients with High Heart Rate:  [[  2  40  85 140 110]
 [  4  35  90 150  95]
 [  5  50  88 145 130]]


## Find all patients where: BP > 140 OR Sugar > 140

In [40]:

import numpy as np

# [PatientID, Age, HeartRate, BP, SugarLevel]
patients = np.array([
    [1, 25, 72, 120, 90],
    [2, 40, 85, 140, 110],
    [3, 60, 78, 130, 150],
    [4, 35, 90, 150, 95],
    [5, 50, 88, 145, 130]
])

critical = patients[(patients[:,3]>140) | (patients[:,4]>140)]


print("Critical patients: ", critical)
print(" No of Critical Patients: ", len(critical))



Critical patients:  [[  3  60  78 130 150]
 [  4  35  90 150  95]
 [  5  50  88 145 130]]
 No of Critical Patients:  3


##  Patients with Normal Sugar

In [41]:
normal_sugar = patients[patients[:,4]<100]
print("Patients with normal sugar: ",normal_sugar)

Patients with normal sugar:  [[  1  25  72 120  90]
 [  4  35  90 150  95]]


##  Average Health Score

In [56]:
hr  = patients[:,2]
print(hr)
bp = patients[:,3]
print(bp)
sugar = patients[:,4]
print(sugar)

average_health = (hr+bp+sugar)/3
print(average_health)


[72 85 78 90 88]
[120 140 130 150 145]
[ 90 110 150  95 130]
[ 94.         111.66666667 119.33333333 111.66666667 121.        ]
