In [1]:
import numpy as np

## Indexing

In [2]:
# Indexing in Vector Array
arr = np.array([1,2,3,4,5,6,7])
print("Indexing: ",arr[3])

#Indexing in Matrices Array
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Matrices Indexing: ", arr[0,2])

#Indexing in Tensors Array
arr = np.array([
    [[1,2,3,4],[5,6,7,8],[9,10,11,12]],
    [[15,16,54,15],[75,65,14,15],[58,65,69,63]]
    ])
print("Matrices Indexing: ", arr[1,2,3])

Indexing:  4
Matrices Indexing:  3
Matrices Indexing:  63


## Slicing 

In [3]:
# Slicing in vector
arr = np.array([10,23,45,65,76])
print("Sliced Array: ", arr[0:3:1])
print("Reversed Array", arr[::-1])
print(" Array: ", arr[::1])


#Slicing in Matrices 

arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array Slicing: ",arr_2d[1,2])
print("Entire row: ",arr_2d[2])
print("Entire Column: ",arr_2d[:,1])

Sliced Array:  [10 23 45]
Reversed Array [76 65 45 23 10]
 Array:  [10 23 45 65 76]
Array Slicing:  6
Entire row:  [7 8 9]
Entire Column:  [2 5 8]


## Question on slicing 

In [4]:
# You have a 1D array of 30 elements representing daily temperatures.
temprature = np.random.randint( 27,42, size=(30))
print("Temprature of Last 30 days: ", temprature)

print("\n")

# Extract the first week’s temperatures.
print("Temprature of the first Week: ", temprature[0:7:1])
print("\n")

# Extract temperatures of alternate days.
print("Alternate Day Temprature: ", temprature[0:31:2])

# Extract the last 10 days.
print("Temprature of last 10 days: ", temprature[-10:])


Temprature of Last 30 days:  [30 30 32 36 33 37 34 37 38 34 30 38 29 32 34 34 28 38 28 34 32 38 31 28
 41 29 39 36 41 41]


Temprature of the first Week:  [30 30 32 36 33 37 34]


Alternate Day Temprature:  [30 32 33 34 38 30 29 34 28 28 32 31 41 39 41]
Temprature of last 10 days:  [32 38 31 28 41 29 39 36 41 41]


## Sorting 

In [5]:
arr = np.array([[1,4,3,67],
                [65,52,45,34],
                [78,56,69,89]])
print("Sorting array Row-wise: ", np.sort(arr, axis = 1))
print("\n")
print("Sorting array Column wise: ", np.sort(arr, axis = 0))

Sorting array Row-wise:  [[ 1  3  4 67]
 [34 45 52 65]
 [56 69 78 89]]


Sorting array Column wise:  [[ 1  4  3 34]
 [65 52 45 67]
 [78 56 69 89]]


## Question on sorting 


In [6]:
arr = np.array([[3789, 1555, 20],
                [95,67, 58],
                [86, 844, 45]])

# Sort the entire array at it wew flat 

print("Flat array: ", arr.flatten())

# Reshape it back into a 3×3 matrix.
print("Reshaped Array: ", arr.reshape(3,3))

# Searching two largest number 
flattened_arr = arr.flatten()
sorted_arr = np.sort(flattened_arr)
result = sorted_arr[-2:]
print("Two largest number: ", result)





Flat array:  [3789 1555   20   95   67   58   86  844   45]
Reshaped Array:  [[3789 1555   20]
 [  95   67   58]
 [  86  844   45]]
Two largest number:  [1555 3789]


In [7]:
arr = np.array([
    ('Alice', 'Gold', 2500),
    ('Bob', 'Silver', 1200),
    ('Charlie', 'Gold', 3000),
    ('David', 'Platinum', 5000)
], dtype=[('name','U10'), ('tier','U10'), ('spend','i4')])

# Sort first by tier alphabetically 

alpha_arr = np.sort(arr, order = 'tier')
print(alpha_arr)

print("\n")

# Within each tier, sort by spend descending.
result = np.sort(alpha_arr,order = 'spend')[::-1]
print(result)




[('Alice', 'Gold', 2500) ('Charlie', 'Gold', 3000)
 ('David', 'Platinum', 5000) ('Bob', 'Silver', 1200)]


[('David', 'Platinum', 5000) ('Charlie', 'Gold', 3000)
 ('Alice', 'Gold', 2500) ('Bob', 'Silver', 1200)]


## Filtering

In [9]:
arr =  np.array([1,2,3,4,5,6,7,8,9])
even_numbers = arr%2 == 0
print("Even_Numbers: ", even_numbers)

Even_Numbers:  [False  True False  True False  True False  True False]


## Filter With Mask

In [ ]:
mask = arr>5
print("number greater than 5: ", arr[mask])

# mask is a function not a variable 

number greater than 5:  [6 7 8 9]


## Adding or removing data 

In [18]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

new_arr = np.concatenate([arr1]+[arr2])
print(new_arr)

[1 2 3 4 5 6]


## Array Compatibilty

In [21]:
a = np.array([12,23,34])
b= np.array([35,566,678])

c= np.array([35,566,678,65])

print("Compatibilty: ", a.shape == b.shape == c.shape)


Compatibilty:  False


## V-Stack and H-Stack 

In [22]:
array_1 = np.array([1,2,3,4])
array_2 = np.array([5,6,7,8])

new_array = np.vstack((array_1,array_2))
print("v-stack: ", new_array)

v-stack:  [[1 2 3 4]
 [5 6 7 8]]


In [23]:
array_1 = np.array([1,2,3,4])
array_2 = np.array([5,6,7,8])

new_array = np.hstack((array_1,array_2))
print("v-stack: ", new_array)

v-stack:  [1 2 3 4 5 6 7 8]
