In [1]:
import numpy as np

## Python Array Vs Numpy Array

In [ ]:
arr_1d = [1,2,3,4]
print("1d_arr: ", arr_1d *2)


np_arr = np.array([1,2,3,4])
print("np_arr: ", np_arr*2)

1d_arr:  [1, 2, 3, 4, 1, 2, 3, 4]
np_arr:  [2 4 6 8]


## arange function in numpy


In [ ]:
arr = np.arange(0,100,5)
print(arr) # It exludes the stop Value  





[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]


## zeroes ones and random function in numpy 

In [ ]:
arr = np.zeros((4,5))
print(arr)

arr = np.ones((8,10))
print(arr)

random =  np.random.random((5,6))
print(random) # Random Values fluctuates between 0 to 1

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[0.0804701  0.52410726 0.79473433 0.46552823 0.1717252  0.40010138]
 [0.38640054 0.48119262 0.73055618 0.34190773 0.08420614 0.68423479]
 [0.77854922 0.46085862 0.25421657 0.72818175 0.13345408 0.69875857]
 [0.76890715 0.43383571 0.41362801 0.44165637 0.06596919 0.28085833]
 [0.88633675 0.4703607  0.80478687 0.92977874 0.83517071 0.38241305]]


## Vector Matrices and Tensor

In [ ]:
#Vector 

vect =  np.array([1,2,3,4])
print("Vectors: ",vect)

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrices: ", matrix)

tens = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print("Tensors: ", tens)

Vectors:  [1 2 3 4]
Matrices:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tensors:  [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


## Array Properties 


In [16]:
arr =  np.array([[1,2,3,4],[5,6,7,8]])
print("Size of the Array: ", arr.size)
print("Dimenstion of the array: ",arr.ndim)
print("Data Type of the Array: ", arr.dtype)
print("Memory Consumed by an Array: ",arr.nbytes)


Size of the Array:  8
Dimenstion of the array:  2
Data Type of the Array:  int64
Memory Consumed by an Array:  64


## Array Reshaping 


In [ ]:
arr = np.arange(12)
print(arr)

reshaped =  arr.reshape((3,4))
print("Reshaped Array: ", reshaped)

flattened = reshaped.flatten()
print("Flattened Array: ", flattened) # It create the copy of array 

arr = flattened.ravel() #It make changes in real array and return the real array
print("Raveled Array: ", arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
