In [2]:
import numpy as np

## Indexing

In [15]:
# Indexing in Vector Array
arr = np.array([1,2,3,4,5,6,7])
print("Indexing: ",arr[3])

#Indexing in Matrices Array
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Matrices Indexing: ", arr[0,2])

#Indexing in Tensors Array
arr = np.array([
    [[1,2,3,4],[5,6,7,8],[9,10,11,12]],
    [[15,16,54,15],[75,65,14,15],[58,65,69,63]]
    ])
print("Matrices Indexing: ", arr[1,2,3])

Indexing:  4
Matrices Indexing:  3
Matrices Indexing:  63


## Slicing 

In [ ]:
# Slicing in vector
arr = np.array([10,23,45,65,76])
print("Sliced Array: ", arr[0:3:1])
print("Reversed Array", arr[::-1])
print(" Array: ", arr[::1])


#Slicing in Matrices 

arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array Slicing: ",arr_2d[1,2])
print("Entire row: ",arr_2d[2])
print("Entire Column: ",arr_2d[:,1])

Sliced Array:  [10 23 45]
Reversed Array [76 65 45 23 10]
 Array:  [10 23 45 65 76]
Array Slicing:  6
Entire row:  [7 8 9]
Entire Column:  [2 5 8]


## Question on slicing 

In [23]:
# You have a 1D array of 30 elements representing daily temperatures.
temprature = np.random.randint( 27,42, size=(30))
print("Temprature of Last 30 days: ", temprature)

print("\n")

# Extract the first week’s temperatures.
print("Temprature of the first Week: ", temprature[0:7:1])
print("\n")

# Extract temperatures of alternate days.
print("Alternate Day Temprature: ", temprature[0:31:2])

# Extract the last 10 days.
print("Temprature of last 10 days: ", temprature[-10:])


Temprature of Last 30 days:  [31 41 27 31 36 35 34 32 33 30 41 35 31 36 34 36 27 38 31 33 34 37 32 29
 38 36 36 39 27 37]


Temprature of the first Week:  [31 41 27 31 36 35 34]


Alternate Day Temprature:  [31 27 36 34 33 41 31 34 27 31 34 32 38 36 27]
Temprature of last 10 days:  [34 37 32 29 38 36 36 39 27 37]


## Sorting 

In [6]:
arr = np.array([[1,4,3,67],
                [65,52,45,34],
                [78,56,69,89]])
print("Sorting array Row-wise: ", np.sort(arr, axis = 1))
print("\n")
print("Sorting array Column wise: ", np.sort(arr, axis = 0))

Sorting array Row-wise:  [[ 1  3  4 67]
 [34 45 52 65]
 [56 69 78 89]]


Sorting array Column wise:  [[ 1  4  3 34]
 [65 52 45 67]
 [78 56 69 89]]


## Question on sorting 


In [23]:
arr = np.array([[3789, 1555, 20],
                [95,67, 58],
                [86, 844, 45]])

# Sort the entire array at it wew flat 

print("Flat array: ", arr.flatten())

# Reshape it back into a 3×3 matrix.
print("Reshaped Array: ", arr.reshape(3,3))

# Searching two largest number 
flattened_arr = arr.flatten()
sorted_arr = np.sort(flattened_arr)
result = sorted_arr[-2:]
print("Two largest number: ", result)





Flat array:  [3789 1555   20   95   67   58   86  844   45]
Reshaped Array:  [[3789 1555   20]
 [  95   67   58]
 [  86  844   45]]
Two largest number:  [1555 3789]


In [48]:
arr = np.array([
    ('Alice', 'Gold', 2500),
    ('Bob', 'Silver', 1200),
    ('Charlie', 'Gold', 3000),
    ('David', 'Platinum', 5000)
], dtype=[('name','U10'), ('tier','U10'), ('spend','i4')])

# Sort first by tier alphabetically 

alpha_arr = np.sort(arr, order = 'tier')
print(alpha_arr)

print("\n")

# Within each tier, sort by spend descending.
result = np.sort(alpha_arr,order = 'spend')[::-1]
print(result)




[('Alice', 'Gold', 2500) ('Charlie', 'Gold', 3000)
 ('David', 'Platinum', 5000) ('Bob', 'Silver', 1200)]


[('David', 'Platinum', 5000) ('Charlie', 'Gold', 3000)
 ('Alice', 'Gold', 2500) ('Bob', 'Silver', 1200)]
