In [2]:

import numpy as np
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]

sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

## Finding the shape of the data 


In [3]:
print("Shape of the sales Data: ", sales_data.shape)

Shape of the sales Data:  (5, 5)


## Finding the data of first 3 restraunt 

In [4]:
print("The required data is: ", sales_data[0:3])

The required data is:  [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


## Total Sales Per year

In [9]:
print("Total sale per Year: ", (np.sum(sales_data, axis = 0)))
yearly_sale  =  np.sum(sales_data[:,1:], axis = 1)
print(yearly_sale)

Total sale per Year:  [     15  810000  945000 1085000 1240000]
[800000 610000 990000 900000 780000]


## Minimum sales  per restraunt

In [24]:
print("Minimum sales of Paradise Biryani: ", np.min(sales_data[:,1:], axis= 1))

Minimum sales of Paradise Biryani:  [150000 120000 200000 180000 160000]


## Maximum Sale per year

In [ ]:
print("Maximum sale in a year: ",  np.max(sales_data[:, 1:], axis = 0))

Maximum sale in a year:  [200000 230000 260000 300000]


## Average Sale per restraunt 

In [28]:
print("Average Sales of Restraunt: ", np.average(sales_data[:,1:],axis = 1))

Average Sales of Restraunt:  [200000. 152500. 247500. 225000. 195000.]
