In [ ]:
import numpy as np

# [VehicleID, EngineCC, Mileage(km/l), HorsePower, Weight(kg), Price, Year]
vehicles = np.array([
    [1, 1200, 18,  90,  1100, 600000, 2018],
    [2, 1500, 15, 110,  1300, 800000, 2020],
    [3, 1800, 12, 140,  1500, 1200000, 2021],
    [4, 1000, 20,  70,   900, 500000, 2017],
    [5, 2000, 10, 180,  1700, 1500000, 2022],
    [6, 1600, 14, 130,  1400, 1000000, 2019],
    [7, 2200,  9, 200,  1800, 1800000, 2023],
    [8, 1400, 16, 100,  1200, 700000, 2020],
    [9, 1300, 17,  95,  1150, 650000, 2018],
    [10,1700, 13, 150,  1550, 1100000, 2021],
    [11,2100, 11, 170,  1650, 1400000, 2022],
    [12,900,  22,  65,   850, 450000, 2016]
])



[[     11    2100      11     170    1650 1400000    2022]
 [      5    2000      10     180    1700 1500000    2022]
 [      7    2200       9     200    1800 1800000    2023]]


## Print top 3 vehicles with highest ratio HorsePower / Weight

In [9]:
ratio = vehicles[:,3]/vehicles[:,4]



sorted_name = np.argsort(ratio)

result = vehicles[sorted_name[-3:]]
print(result)

[[     11    2100      11     170    1650 1400000    2022]
 [      5    2000      10     180    1700 1500000    2022]
 [      7    2200       9     200    1800 1800000    2023]]


## Performance Score (HorsePower * Mileage) / Weight

In [ ]:
performance_score = (vehicles[:,3]*vehicles[:,2])/ vehicles[:,4]

sorted_performance = np.argsort(performance_score)

performance_result = vehicles[sorted_performance[-5:]]

print("Top 5 performance score \n \n ", performance_result)


Top 5 performance score 
 
  [[     8   1400     16    100   1200 700000   2020]
 [     9   1300     17     95   1150 650000   2018]
 [     1   1200     18     90   1100 600000   2018]
 [     4   1000     20     70    900 500000   2017]
 [    12    900     22     65    850 450000   2016]]


## Dominance Score (Multi-metric Ranking)

In [24]:
dominance_performance = (vehicles[:,3] * vehicles[:,2]) / (vehicles[:,1]*vehicles[:,4])
print(dominance_performance)

sorted_dominanace = np.argsort(dominance_performance)

top_4_index = sorted_dominanace[-4:]

result = np.column_stack((vehicles[top_4_index, 0], dominance_performance[top_4_index]))

print(" Dominance Score Multi-metric Ranking",result)



[0.00122727 0.00084615 0.00062222 0.00155556 0.00052941 0.0008125
 0.00045455 0.00095238 0.00108027 0.00074004 0.00053968 0.00186928]
 Dominance Score Multi-metric Ranking [[9.00000000e+00 1.08026756e-03]
 [1.00000000e+00 1.22727273e-03]
 [4.00000000e+00 1.55555556e-03]
 [1.20000000e+01 1.86928105e-03]]
